# Generated by Django 5.0 on 2024-02-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0002_rename_text2image_imagetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetext',
            name='image',
            field=models.ImageField(default='/webcapture2_vHTTufR.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagetext',
            name='text_from_image',
            field=models.TextField(default='Text generated by the ocr'),
        ),
    ]
