# Generated by Django 5.0 on 2024-02-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0004_alter_imagetext_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetext',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagetext',
            name='text_from_image',
            field=models.TextField(null=True),
        ),
    ]
