# Generated by Django 5.0 on 2024-02-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0005_alter_imagetext_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetext',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='imagetext',
            name='text_from_image',
            field=models.TextField(),
        ),
    ]
